import pandas
from models.save_load import SaveLoad


a = [
    [
        [
            [
                "efef",
                1
            ],
            [
                "iklki",
                0
            ]
        ],
        [
            [
                "sdgrfgf",
                0
            ],
            [
                "drgdg",
                1
            ]
        ],
        [
            [
                "grfgrf",
                0.5
            ],
            [
                "sdgsthg",
                0.5
            ]
        ],
        [
            [
                "dht",
                0
            ],
            [
                "gfhj",
                1
            ]
        ]
    ],
    [
        [
            [
                "efef",
                2
            ],
            [
                "drgdg",
                1
            ]
        ],
        [
            [
                "gfhj",
                1.5
            ],
            [
                "grfgrf",
                1.0
            ]
        ],
        [
            [
                "sdgsthg",
                1.0
            ],
            [
                "iklki",
                0.5
            ]
        ],
        [
            [
                "sdgrfgf",
                0.5
            ],
            [
                "dht",
                0.5
            ]
        ]
    ],
    [
        [
            [
                "efef",
                2.5
            ],
            [
                "gfhj",
                2.0
            ]
        ],
        [
            [
                "drgdg",
                1.5
            ],
            [
                "grfgrf",
                1.5
            ]
        ],
        [
            [
                "sdgsthg",
                1.5
            ],
            [
                "iklki",
                1.0
            ]
        ],
        [
            [
                "sdgrfgf",
                1.0
            ],
            [
                "dht",
                1.0
            ]
        ]
    ],
    [
        [
            [
                "efef",
                3.5
            ],
            [
                "gfhj",
                3.0
            ]
        ],
        [
            [
                "drgdg",
                2.5
            ],
            [
                "grfgrf",
                2.5
            ]
        ],
        [
            [
                "sdgsthg",
                2.5
            ],
            [
                "iklki",
                2.0
            ]
        ],
        [
            [
                "sdgrfgf",
                2.0
            ],
            [
                "dht",
                2.0
            ]
        ]
    ]
]



def check_round_statute(tournament_name, current_round_nb):
        round_name = "Round" + " " + str(current_round_nb)
        selected_round = SaveLoad.selected_archive("Round_name", round_name, file_name=("rounds_info/" + tournament_name))
        End_date_time = selected_round["End_date_time"]
        return End_date_time
    
"In progress"
g = check_round_statute("eeee", 1)
print(g)
